# name: Despair
# author: al1-ce
# license: MIT
# blurb: despair

[colors]
ansi = [
  "#101010", # 0  Black
  "#903a3a", # 1  Red
  "#6d7144", # 2  Green
  "#af8431", # 3  Yellow
  "#50616f", # 4  Blue
  "#92729f", # 5  Purple
  "#61837e", # 6  Cyan
  "#7c7c7c", # 7  White
]
brights = [
  "#8e8e8e", # 8  Black
  "#ce5252", # 9  Red
  "#9ca54e", # 10 Green
  "#f0c674", # 11 Yellow
  "#5f819d", # 12 Blue
  "#b48ac4", # 13 Purple
  "#73b8af", # 14 Cyan
  "#b9b9b9", # 15 White
]
foreground = "#b9b9b9"
background = "#101010"

cursor_bg = "#101010"
cursor_border = "#b9b9b9"
cursor_fg = "#b9b9b9"
selection_bg = "#b9b9b9"
selection_fg = "#101010"

[colors.indexed]

[metadata]
aliases = ["Despair"]
name = "despair"
origin_url = "https://github.com/al1-ce/monolith.nvim"
wezterm_version = "Always"


